spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.89:3306/springcloud_sell?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  rabbitmq:
    host: 192.168.159.136
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.159.136 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: root #Redis服务器接连密码(默认为空)
  jpa:
    show-sql: true
