spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
